// This file is generated by the `updateUnicodeData` Gradle task.
// Source: https://www.unicode.org/Public/16.0.0/ucd/DerivedCoreProperties.txt (Default_Ignorable_Code_Point)
// Unicode version: 16.0.0
// Do not edit by hand.

package doist.x.confusables

internal object DefaultIgnorables {
    internal const val UNICODE_VERSION: String = "16.0.0"

    // Inclusive ranges: [start0, end0, start1, end1, ...]
    private val ranges: IntArray = intArrayOf(
        0xAD, 0xAD, 0x34F, 0x34F, 0x61C, 0x61C, 0x115F, 0x1160,
        0x17B4, 0x17B5, 0x180B, 0x180F, 0x200B, 0x200F, 0x202A, 0x202E,
        0x2060, 0x206F, 0x3164, 0x3164, 0xFE00, 0xFE0F, 0xFEFF, 0xFEFF,
        0xFFA0, 0xFFA0, 0xFFF0, 0xFFF8, 0x1BCA0, 0x1BCA3, 0x1D173, 0x1D17A,
        0xE0000, 0xE0FFF,
    )

    internal fun isDefaultIgnorable(codePoint: Int): Boolean {
        var low = 0
        var high = (ranges.size / 2) - 1
        while (low <= high) {
            val mid = (low + high) ushr 1
            val start = ranges[mid * 2]
            val end = ranges[mid * 2 + 1]
            when {
                codePoint < start -> high = mid - 1
                codePoint > end -> low = mid + 1
                else -> return true
            }
        }
        return false
    }
}
